# site settings
title: Tem acordo
email: prensa@ciudadanointeligente.org
description: La Reforma al Financiamiento de la Política es clave para el fortalecimiento de las confianzas entre los ciudadanos y sus autoridades o representantes. Los ciudadanos abogamos por una reforma y el Gobierno envió su Proyecto de Ley... pero Hay Acuerdo?
baseurl: https://temacordonasmetas.cidadaniainteligente.org
basedomain: temacordonasmetas.cidadaniainteligente.org
analytics: "UA-41822715-4"

# Governança
gsheetgovernanca: "https://docs.google.com/spreadsheets/d/1j7XjeGe4OJ8vYtDwx_ipOvR0z5gsafVnh9b37-CJ58A/pubhtml"
# first page to load
gsheetgovernanca-sheetpage: "governanca-governanca"

# twitter
twitter:
  username: '@ciudadanoi'

# build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
